name: Send allure results

on:
  workflow_run:
    workflows: ['pages-build-deployment']
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: Allure report is successfully deployed on GitHub Pages. Use the link from first notification to open it.
          SLACK_MSG_AUTHOR: ${{github.actor}}
          SLACK_TITLE: Message
          SLACK_USERNAME: tide-automation
          SLACK_FOOTER: Repository ${{ github.repository }}
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: Build is failed.
          SLACK_MSG_AUTHOR: ${{github.actor}}
          SLACK_TITLE: Message
          SLACK_USERNAME: tide-automation
          SLACK_FOOTER: Repository ${{ github.repository }}
